name: Build and Push HMD Kernel Repos

on:
  workflow_dispatch:
    inputs:
      device_name:
        description: 'Device name to build (e.g., "Nokia 3")'
        required: true
        type: string
  schedule:
    - cron: '0 2 * * 0'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is for the checkout action, not the PAT

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      # --- This is an optional but helpful debugging step ---
      - name: Verify Secret is Present
        run: |
          if [ -z "${{ secrets.HMD_ARCHIVE_TOKEN }}" ]; then
            echo "Error: HMD_ARCHIVE_TOKEN secret is not set or is empty."
            exit 1
          else
            echo "Secret is present. Proceeding."
          fi

      - name: Run for a specific device (Manual Trigger)
        if: github.event_name == 'workflow_dispatch'
        env:
          # Use GH_TOKEN instead of GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.HMD_ARCHIVE_TOKEN }}
        run: |
          chmod +x ./build_and_push.sh
          ./build_and_push.sh "${{ github.event.inputs.device_name }}"

      - name: Run for all devices (Scheduled Trigger)
        if: github.event_name == 'schedule'
        env:
          # Use GH_TOKEN instead of GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.HMD_ARCHIVE_TOKEN }}
        run: |
          # ... (The rest of this step remains the same)
          chmod +x ./build_and_push.sh
          JSON_REPO="crsvt/hmd-opensource-tracker"
          JSON_URL="https://raw.githubusercontent.com/${JSON_REPO}/main/hmd_versions.json"
          echo "Fetching device list from $JSON_URL"
          DEVICE_LIST=$(curl -sL "$JSON_URL" | jq -r 'keys[]')
          while IFS= read -r device; do
            echo "-----------------------------------------------------"
            echo "Processing device: $device"
            echo "-----------------------------------------------------"
            ./build_and_push.sh "$device"
          done <<< "$DEVICE_LIST"