name: Build and Push HMD Kernel Repos

on:
  workflow_dispatch:
    inputs:
      device_name:
        description: 'Device name to build (e.g., "Nokia 3")'
        required: true
        type: string
  schedule:
    - cron: '0 2 * * 0'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      # MANUAL TRIGGER: Pass the secret and device name as arguments
      - name: Run for a specific device (Manual Trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          chmod +x ./build_and_push.sh
          ./build_and_push.sh "${{ secrets.HMD_ARCHIVE_TOKEN }}" "${{ github.event.inputs.device_name }}"

      # SCHEDULED TRIGGER: Loop and pass the secret and device name as arguments
      - name: Run for all devices (Scheduled Trigger)
        if: github.event_name == 'schedule'
        run: |
          chmod +x ./build_and_push.sh
          JSON_REPO="crsvt/hmd-opensource-tracker"
          JSON_URL="https://raw.githubusercontent.com/${JSON_REPO}/main/hmd_versions.json"
          DEVICE_LIST=$(curl -sL "$JSON_URL" | jq -r 'keys[]')

          while IFS= read -r device; do
            echo "-----------------------------------------------------"
            echo "Processing device: $device"
            echo "-----------------------------------------------------"
            ./build_and_push.sh "${{ secrets.HMD_ARCHIVE_TOKEN }}" "$device"
          done <<< "$DEVICE_LIST"