name: Build and Push HMD Kernel Repos

on:
  workflow_dispatch:
    inputs:
      device_name:
        description: 'Device name to build (e.g., "Nokia 3.1")'
        required: true
        type: string
  schedule:
    - cron: '0 3 * * 3,5'

jobs:
  # Job 1: (SCHEDULE ONLY) Get the list of all devices
  get-devices:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    outputs:
      devices: ${{ steps.set-matrix.outputs.devices }}
    steps:
      - id: set-matrix
        run: |
          JSON_URL="https://raw.githubusercontent.com/crevanth/hmd-oss-scraper/main/data/hmd_releases.json"
          DEVICE_LIST=$(curl -sL "$JSON_URL" | jq -c 'keys')
          echo "devices=$DEVICE_LIST" >> $GITHUB_OUTPUT

  # Job 2A: (MANUAL TRIGGER ONLY) Build a single device
  build-for-manual-trigger:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Run for device - ${{ github.event.inputs.device_name }}
        run: |
          chmod +x ./import_kernel_sources.sh
          ./import_kernel_sources.sh "${{ secrets.HMD_ARCHIVE_TOKEN }}" "${{ github.event.inputs.device_name }}"

  # Job 2B: (SCHEDULE ONLY) Build all devices in parallel
  build-for-schedule:
    if: github.event_name == 'schedule'
    needs: [get-devices] # This job depends on the device list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device_name: ${{ fromJson(needs.get-devices.outputs.devices) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Run for device - ${{ matrix.device_name }}
        run: |
          chmod +x ./import_kernel_sources.sh
          ./import_kernel_sources.sh "${{ secrets.HMD_ARCHIVE_TOKEN }}" "${{ matrix.device_name }}"
      - name: Report failure as a GitHub Issue
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // (Your issue reporting script here)

  # Job 3: (SCHEDULE ONLY) Update the dashboard
  update-dashboard:
    if: always() && github.event_name == 'schedule'
    needs: [build-for-schedule] # Depends on the scheduled build job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Update Organization Profile README
        run: |
          chmod +x ./update_dashboard.sh
          ./update_dashboard.sh "${{ secrets.HMD_ARCHIVE_TOKEN }}"
