name: Build and Push HMD Kernel Repos

on:
  workflow_dispatch:
    inputs:
      device_name:
        description: 'Device name to build (e.g., "Nokia 3.1")'
        required: true
        type: string
  schedule:
    - cron: '0 2 * * 0' # Runs every Sunday at 02:00 UTC

jobs:
  # This job gets the list of devices to process for the scheduled run
  get-devices:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    outputs:
      devices: ${{ steps.set-matrix.outputs.devices }}
    steps:
      - id: set-matrix
        run: |
          JSON_URL="https://raw.githubusercontent.com/crevanth/hmd-oss-scraper/main/data/hmd_releases.json"
          DEVICE_LIST=$(curl -sL "$JSON_URL" | jq -c 'keys')
          echo "devices=$DEVICE_LIST" >> $GITHUB_OUTPUT

  # This job processes each device, either from a manual trigger or the matrix
  build-and-publish:
    # This makes the scheduled run depend on the get-devices job
    needs: [get-devices]
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # IMPORTANT: Allows other jobs to continue if one fails
      matrix:
        # For scheduled runs, use the device list from the previous job
        # For manual runs, create a single-item array from the input
        device_name: ${{ github.event_name == 'schedule' && fromJson(needs.get-devices.outputs.devices) || fromJson(format('["{0}"]', github.event.inputs.device_name)) }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run for device - ${{ matrix.device_name }}
        run: |
          chmod +x ./import_kernel_sources.sh
          ./import_kernel_sources.sh "${{ secrets.HMD_ARCHIVE_TOKEN }}" "${{ matrix.device_name }}"

      # THIS IS THE NEW STEP FOR FAILURE NOTIFICATION
      - name: Report failure as a GitHub Issue
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deviceName = "${{ matrix.device_name }}";
            const issueTitle = `[AUTO] Kernel Processing Failure: ${deviceName}`;
            const issueBody = `
            🚨 **An error occurred while processing the kernel for \`${deviceName}\`.**

            The workflow failed and requires manual investigation.

            - **Workflow Run:** [Link to failed run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['bug', 'automation-failure']
            });
