name: Build and Push HMD Kernel Repos

on:
  workflow_dispatch:
    inputs:
      device_name:
        description: 'Device name to build (e.g., "Nokia 3.1")'
        required: true
        type: string
  schedule:
    - cron: '0 2 * * 0' # Runs every Sunday at 02:00 UTC

jobs:
  # Job 1: Get the list of devices to process for the scheduled run
  get-devices:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    outputs:
      devices: ${{ steps.set-matrix.outputs.devices }}
    steps:
      - id: set-matrix
        run: |
          JSON_URL="https://raw.githubusercontent.com/crevanth/hmd-oss-scraper/main/data/hmd_releases.json"
          DEVICE_LIST=$(curl -sL "$JSON_URL" | jq -c 'keys')
          echo "devices=$DEVICE_LIST" >> $GITHUB_OUTPUT

  # Job 2: Process each device in parallel (using a matrix)
  build-and-publish:
    needs: [get-devices]
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Allows other jobs to continue even if one device fails
      matrix:
        device_name: ${{ github.event_name == 'schedule' && fromJson(needs.get-devices.outputs.devices) || fromJson(format('["{0}"]', github.event.inputs.device_name)) }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run for device - ${{ matrix.device_name }}
        run: |
          chmod +x ./import_kernel_sources.sh
          ./import_kernel_sources.sh "${{ secrets.HMD_ARCHIVE_TOKEN }}" "${{ matrix.device_name }}"

      - name: Report failure as a GitHub Issue
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deviceName = "${{ matrix.device_name }}";
            const issueTitle = `[AUTO] Kernel Processing Failure: ${deviceName}`;
            const issueBody = `
            🚨 **An error occurred while processing the kernel for \`${deviceName}\`.**

            The workflow failed and requires manual investigation.

            - **Workflow Run:** [Link to failed run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['bug', 'automation-failure']
            });

  # Job 3: Update the organization dashboard after all devices are processed
  update-dashboard:
    runs-on: ubuntu-latest
    # This job must wait for all parallel build jobs to complete
    needs: build-and-publish
    # 'if: always()' ensures this runs even if some devices failed.
    # We only run this for the scheduled, full-system run.
    if: always() && github.event_name == 'schedule'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Update Organization Profile README
        run: |
          chmod +x ./update_dashboard.sh
          ./update_dashboard.sh "${{ secrets.HMD_ARCHIVE_TOKEN }}"
